name: Terraform Workflow

on:
  - push
  - workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.TERRAFORM_GOOGLE_CREDENTIALS }}'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_project_id: ${{ vars.project_id }}
          TF_VAR_service_account_id: ${{ vars.service_account_id }}
          TF_VAR_region_name: ${{ vars.region_name }}
          TF_VAR_bucket_name: ${{ vars.bucket_name }}

        run: ./scripts/apply
      
      - name: Generate Output
        id: terraform-output
        run: |
          terraform output -json > outputs.json

      - uses: actions/upload-artifact@v4
        with:
          name: terraform_output
          path: ./outputs.json
